name: Build

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository master branch
          uses: actions/checkout@master
  
        - name: Setup Node.js 20.x
          uses: actions/setup-node@master
          with:
            node-version: '20.x'
  
        - name: Setup NextJS Dependencies
          run: |
            yarn install
            yarn docs:build
  
        - name: Set cdn-moeyy-cn Config
          uses: manyuanrong/setup-ossutil@master
          with:
            endpoint: oss-cn-hongkong.aliyuncs.com
            access-key-id: ${{ secrets.OSS_KEY }}
            access-key-secret: ${{ secrets.OSS_SECRET }}
        - name: Delete files
          run: ossutil rm -r -f oss://rsshub-docs/
        - name: Upload files
          run: ossutil cp -j 100 -rf .vitepress/dist/ oss://rsshub-docs/